### PR TITLE
Fixed webpack5 issue, dynamic requires now returns a module instead of a string

### LINKED ISSUE #1: Add support for webpack 5
Please Add support for webpack 5 :)

```
 Error: Can't find template for: ReadonlyField
    at _getTemplateFor (view-engine.js:172)
    at makeVueComponent (view-engine.js:182)
    at eval (fw.js:97)
    at Array.forEach (<anonymous>)
    at FrameworkConfig.registerComponents (fw.js:96)```

### PR DESCRIPTION
**Pull request by niemyjski**
Fixes https://github.com/derekpitt/fw-loader/issues/1

I was unable to run the tests due to really old gulp/mocha dependencies that wouldn't stop complaining on latest node lts but I tested in the browser. I also tweaked the generated javascript slightly as it wanted to include the following helper function which was not needed.

```js
var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };
```

Can we merge this and push 0.3.4

### CODE REVIEW

**Comment by niemyjski** [comment]
Also worth nothing I could submit a branch where most of the deps are updated but tests wouldn't run due to some crazy issues with babel transpilation / mocha

**Comment by raiseandfall** [comment]
We should probably consider ~~running~~ moving away from Gulp and use Rollup.

**Comment by niemyjski** [comment]
I'd prefer esbuild :)
Thanks
-Blake Niemyjski

**Comment by raiseandfall** [comment]
Yeah, anything other than gulp ahah

**Comment by niemyjski** [comment]
@derekpitt any updates?

**Pull request merged**
